name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  APP_NAME: cron-ticker

jobs:
  build:
    runs-on: ubuntu-latest

    # Variables a nivel del job
    env:
      BUILD_DIR: dist

    steps:
      - uses: actions/checkout@v4

      - name: Show Variables
        run: |
          echo "App: ${{ env.APP_NAME }}, Node: ${{ vars.NODE_VERSION }}"

      - name: Show Github Variables
        run: |
          echo "App Version: ${{ vars.APP_VERSION }}"

      # Variables a nivel del step
      - name: Build
        run: npm run build
        env:
          APP_VERSION: '2.0.0'
